# Generated by Django 4.0.6 on 2023-04-14 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Usertable',
        ),
    ]
