# Generated by Django 4.0.6 on 2023-04-15 13:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_rename_user_usertable'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='task',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
